[google]
type = "service_account"
project_id = "peak-tract-459716-g2"
private_key_id = "9136028f6279247ad3095ebe818dd03abb0b8d66"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDwMd5PpzEtI0te
LY3WMveJ2TDqVZKjtk53aifFkxvw7bTW1yJ9v3bj+3yzXJbxfJmhj5vxK7Tphpex
5Iioy28IOID/C/LQ8fQwU5tNaxQuVVfL+CydXEhT8+lm1Y1YmMxxwAQ1Yfr/vWe5
4LRAPMK7d3LPvK9BoBxrGAmZldgwO1DlwqsfEjCQrAVYmMG1YJ2Ob4bpxcT4N5jC
oSoqZ7t+qo1nW1rzbB3Q1thcBlHW9gVeY7pXEsJdCr4XS+3wXdGWbYIXXqwFd4r4
AByDUieeyG3drUQk6opJj1Xr+Y/rf7M2ZT+tjA2nZ72af0UzRku1zYxPAnEFEOO3
Bem+REAJAgMBAAECggEAA33yrj1YYFKwreMMXw57WPRXmxGv2JQs3JO4ld+uI8/E
UTZsMbusgXVKCAnOWWf9+cuKDKJ5Guu/79TKX4uQdJsRsQgeFNCTH1K9j1al+a0K
YjkcXYIovHYBsQeJ6nRTYJRD//gcDbTDlTbdBbZX20W3poTLhFWoWveoSBJoH0db
/QagZeJvuK8uT5JHBYn/QxpwlaR9AS69woMP7Defa51S5j4gpeHrkjcwOeNkcGFQ
44lrJK/aQByBEPejZBIRlUoTWY9s7YZP0DFIxyptHVTuKnNOtXADmViDeP8QuE7P
+Bl7uuzXJWgtZq+yK/JL5akcOgKccRH6RYcmzS5+uwKBgQD6oICMTYJd44YjhnLZ
IQyso4Kidqy1QBOHESQ4uGej3koG7Oo3fDP4VXutbYJCPrer/qaoMGL2ne4GyFXC
S7eu3fFvOzfHPftomBbAGLlC/xe4b5g8ZeJg2joOrYC6TBSChFDWJJA9COVyCeXR
PCAjOmGbKL1we0TIGbN/1sJ6GwKBgQD1WBy3fJsKeRZqMBtY4b4lBAgYJkXG+YTe
eqDFzgNWTQTSq9WjIIzBqr9xCcFxyKJrfgR5R2jv7s/weCtLD8noAzajeO7RfFKl
jLyYJ6O853SoeBuDQbT0lHBoIt0rO7VZjz14kVUTg1elF9F5SBvbEuG22cas1RH4
ZWEQg+EQqwKBgHnXz8bl46wrccoRkgIXPCct8tNy6HHRbezrG3XryI71AX4ubYt9
+XIQdOkSZRI5lWerjHAV3fbRPqfTe0XTM8Byq+6MlohpjLEDx4OqQV7dzzVeI1+x
lIXLchAyr3Nii1IMa5RAAFN74Lg5MZ4wIduehVc+TiLB+uVhAU/0I2XjAoGACvj0
19PvzykZMoiSQIhgC6HBhur3Re3U3mpXlGEhTxPEunNK66/B+8taIoEQMLmLYglR
w+bIr6pbjGKjdQjwu7qhD/CRpbbMr3C64ocrUIB9fCda+6TNpf6ZhF7Cy3MxKh84
3ZKKXoQKQGzvRmBONp8Cjz3wH7yrwBMwox9yyl8CgYAMBukTgjQ23I8SCSaWvF6X
DWhKtbUksrfHHVB9fOKPgMiZPv0ZT96KBMcsDifLy1d5SIF41cRj7Z7sRbtv1Uza
oCcqTB173x5BZjSIGMq2Fvw7VayfiizSiGpOMZiFq9GnQrhBVk2m/zImaEQ8/BIk
0zY3169n3wgyt94Rggg+6g==
-----END PRIVATE KEY-----"""
client_email = "jantenucci@peak-tract-459716-g2.iam.gserviceaccount.com"
client_id = "106358975049855304025"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/jantenucci%40peak-tract-459716-g2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
