[google]
type = "service_account"
project_id = "peak-tract-459716-g2"
private_key_id = "9136028f6279247ad3095ebe818dd03abb0b8d66"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkq...
...tu clave privada completa aquí...
...6g==\n-----END PRIVATE KEY-----\n"""
client_email = "jantenucci@peak-tract-459716-g2.iam.gserviceaccount.com"
client_id = "106358975049855304025"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/jantenucci%40peak-tract-459716-g2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
